workflows:
  ios-trollstore:
    name: Build pour TrollStore
    instance_type: mac_mini_m1
    max_build_duration: 30
    environment:
      node: 20
      xcode: latest
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Expo prebuild
        script: npx expo prebuild --platform ios --no-install
      - name: Install Pods
        script: |
          cd ios
          pod install
      - name: Build unsigned .app
        script: |
          cd ios
          mkdir -p ../dist
          # On change un peu la commande pour aider le compilateur Swift
          xcodebuild build \
            -workspace *.xcworkspace \
            -scheme $(ls -d *.xcworkspace | cut -d. -f1) \
            -configuration Release \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            CONFIGURATION_BUILD_DIR=../dist \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            AD_HOC_CODE_SIGNING_ALLOWED=YES \
            STRIP_INSTALLED_PRODUCT=NO \
            GCC_GENERATE_DEBUGGING_SYMBOLS=NO
      - name: Package IPA
        script: |
          mkdir Payload
          cp -r dist/*.app Payload/
          zip -r MySecretApp.ipa Payload
    artifacts:
      - "*.ipa"